import RPi.GPIO as GPIO # RPi.GPIOモジュールを使用
import time


# グローバル変数を設定

SENSOR1-INPUT = 10
SENSOR2-INPUT =11
SENSOR3-INPUT =13

SENSOR1-OUTPUT =14
SENSOR2-OUTPUT =15
SENSOR3-OUTPUT =16


# GPIO を設定する

GPIO.setmode(GPIO.BCM)

GPIO.setup(SENSOR1-INPUT,GPIO.IN)
GPIO.setup(SENSOR2-INPUT,GPIO.IN)
GPIO.setup(SENSOR3-INPUT,GPIO.IN)


GPIO.setup(SENSOR1-OUTPUT,GPIO.OUT)
GPIO.setup(SENSOR2-OUTPUT,GPIO.OUT)
GPIO.setup(SENSOR3-OUTPUT,GPIO.OUT)


